<?php

/**
 * @file
 * Contains ckeditor_abbreviation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function ckeditor_abbreviation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ckeditor_abbreviation':
      $output = '';
      $output .= '<h3>' . t('CKEditor Abbreviation') . '</h3>';
      $output .= '<p>' . t('The module adds a CKEditor abbreviation button to the editor toolbar and a link to its context menu (only available if you select an existing abbr tag in the editor content).') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Settings') . '</dt>';
      $output .= '<dd>' . t('In the <a href=":text-formats">text formats</a> that use ckeditor, move the icon into the active toolbar.', [':text-formats' => Url::fromRoute('filter.admin_overview')->toString()]) . '</dd>';
      $output .= '<dt>' . t('Usage') . '</dt>';
      $output .= '<dd>' . t('Select the abbreviation you want to tag. Click the ckeditor abbreviation icon and fill in the fields in the opening dialog.') . '</dd>';
      $output .= '<dd>' . t('To edit a tagged abbreviation place the cursor within the abbreviation text and click the ckeditor abbreviation icon. Or open the context menu by right-clicking on your mouse and select "Edit Abbreviation".') . '</dd>';
      $output .= '<dd>' . t('To remove an abbreviation title attribute, delete the explanation in the ckeditor abbreviation dialog. In order to untag an abbreviation, delete the abbreviation in the ckeditor abbreviation dialog.') . '</dd>';
      $output .= '</dl>';
      return $output;
    default:
  }
}
