<?php

/**
 * @file
 * Enable the "glightbox inline" functionality.
 */
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\glightbox_inline\Hook\GlightboxInlineHooks;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_page_attachments().
 */
#[LegacyHook]
function glightbox_inline_page_attachments(array &$page)
{
    \Drupal::service(GlightboxInlineHooks::class)->pageAttachments($page);
}

/**
 * Implements hook_help().
 */
#[LegacyHook]
function glightbox_inline_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(GlightboxInlineHooks::class)->help($route_name, $route_match);
}
