<?php

/**
 * Implements hook_module_implements_alter().
 *
 * Ensure custom_uml_mail runs last when hook_mail_alter is invoked.
 */
function custom_uml_blogs_mail_module_implements_alter(&$implementations, $hook) {
  if (($hook == 'mail_alter' || $hook == 'mail') && isset($implementations['custom_uml_blogs_mail'])) {
    $group = $implementations['custom_uml_blogs_mail'];
    unset($implementations['custom_uml_blogs_mail']);
    $implementations['custom_uml_blogs_mail'] = $group;
    // If the reroute_email module is installed, ensure that comes after ours so
    // rerouted emails are still rerouted.
    if (isset($implementations['reroute_email'])) {
      $group = $implementations['reroute_email'];
      unset($implementations['reroute_email']);
      $implementations['reroute_email'] = $group;
    }
  }
}

/**
 * Implements hook_mail_alter().
 *
 * Alter destination of outgoing emails to group members.
 */
function custom_uml_blogs_mail_mail_alter(&$message) {
  if ($message['id'] == 'content_moderation_notifications_content_moderation_notification') {
    $node = $message['params']['context']['entity'];
    $group_node = \Drupal\node\Entity\Node::load($node->get('og_audience')->target_id);
    $memberships = \Drupal::service('og.membership_manager')->getGroupMembershipsByRoleNames($group_node, ['member']);
    $bcc = '';
    foreach ($memberships as $membership) {
      $bcc .= $membership->getOwner()->getEmail() . ',';
    }
    $message['bcc'] = rtrim($bcc, ',');
    $message['headers']['Bcc'] = $message['bcc'];
    \Drupal::messenger()->addMessage('All subscribers of ' . $group_node->getTitle() . ' have been sent a notification email.');
  }
}
