<?php

/**
 * Implements hook_module_implements_alter().
 *
 * Ensure custom_uml_mail runs last when hook_mail_alter is invoked.
 */
function custom_uml_blogs_mail_module_implements_alter(&$implementations, $hook) {
  if (($hook == 'mail_alter' || $hook == 'mail') && isset($implementations['custom_uml_blogs_mail'])) {
    $group = $implementations['custom_uml_blogs_mail'];
    unset($implementations['custom_uml_blogs_mail']);
    $implementations['custom_uml_blogs_mail'] = $group;
    // If the reroute_email module is installed, ensure that comes after ours so
    // rerouted emails are still rerouted.
    if (isset($implementations['reroute_email'])) {
      $group = $implementations['reroute_email'];
      unset($implementations['reroute_email']);
      $implementations['reroute_email'] = $group;
    }
  }
}

/**
 * Implements hook_mail_alter().
 *
 * Alter destination of outgoing emails to group members.
 */
function custom_uml_blogs_mail_mail_alter(&$message) {
  if (($message['id'] ?? '') == 'content_moderation_notifications_content_moderation_notification') {
    $node = $message['params']['context']['entity'] ?? NULL;
    if (!$node instanceof \Drupal\node\NodeInterface || !$node->hasField('og_audience') || $node->get('og_audience')->isEmpty()) {
      return;
    }
    $group_node = \Drupal\node\Entity\Node::load($node->get('og_audience')->target_id);
    if (!$group_node) {
      return;
    }
    $memberships = \Drupal::service('og.membership_manager')->getGroupMembershipsByRoleNames($group_node, ['member']);
    $bcc_emails = [];
    $validator = \Drupal::service('email.validator');
    foreach ($memberships as $membership) {
      $email = $membership->getOwner()->getEmail();
      if (!empty($email) && $validator->isValid($email)) {
        $bcc_emails[$email] = $email;
      }
    }
    if (empty($bcc_emails)) {
      return;
    }
    $bcc = implode(',', $bcc_emails);
    $subject = str_replace(
      '[node:og_audience:entity:title]: [node:title]',
      $group_node->getTitle() . ': ' . $node->getTitle(),
      (string) ($message['params']['subject'] ?? '')
    );
    \Drupal::logger('custom_uml_blogs_mail')->notice('Message %subject sent to %count subscribers',
    [
      '%subject' => $subject,
      '%count' => count($bcc_emails),
    ]);
    $message['bcc'] = $bcc;
    if (!isset($message['headers']) || !is_array($message['headers'])) {
      $message['headers'] = [];
    }
    $message['headers']['Bcc'] = $bcc;
  }
}
