<?php

/**
 * Implements hook_link_alter().
 */
function custom_blogs_link_alter(&$vars) {
  if (
    $vars['url']->isRouted()
    && $vars['url']->getRouteName() === 'user.page'
    && (string) $vars['text'] === (string) t('My account')
  ) {
    $vars['text'] = t('@name', ['@name' => \Drupal::currentUser()->getDisplayName()]);
    $vars['url'] = \Drupal\Core\Url::fromUri('route:<nolink>');
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Change tab names.
 */
function custom_blogs_menu_local_tasks_alter(&$data, $route_name) {
  if ($route_name === 'entity.node.canonical') {
    /** @var \Drupal\node\Entity\Node $node */
    $node = \Drupal::routeMatch()->getParameter('node');
    $bundles = ['blog', 'blog_post'];
    if ($node && in_array($node->bundle(), $bundles)) {
      $bundle_label = str_replace('Blog ', '', $node->type->entity->label());
      $data['tabs'][0]['entity.node.edit_form']['#link']['title'] = 'Edit '.$bundle_label;
      $data['tabs'][0]['og.og_admin_routes:node.og_admin_routes']['#link']['title'] = 'Blog Members';
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function custom_blogs_form_views_exposed_form_alter(array &$form, $form_state, $form_id) {
  $path = \Drupal::service('path.current')->getPath();
  $view = $form_state->getStorage('view');
  if (($view['view']->id() == 'all_posts') && ($view['view']->current_display == 'block_1')) {
    //This moves the search button to the search box.
    $actions['actions'] = $form['actions'];
    unset($form['actions']);
    $positions = array_keys($form);
    $keys_position = array_search('keys', $positions);
    //Note that to actually move actions, it needs to be set within a numerically keyed array.
    array_splice($form, $keys_position + 1, 0, [$actions]);
  }
  //Unset these if we arent on the all-posts page with optional date
  if (($view['view']->id() == 'all_posts') && (!strpos($path, 'all-posts'))) {
    unset($form['keys']['#title']);
    unset($form['#info']['filter-keys']['label']);
    unset($form['blog']);
  }
  if (($view['view']->id() == 'recent_posts') && ($view['view']->current_display == 'block_1')) {
    //This alters the title of the search box and adds a reset link.
    $node = \Drupal::routeMatch()->getParameter('node');
    $form['keys']['#title'] = $form['keys']['#title'] . ' ' . $node->getTitle();
    $form['#info']['filter-keys']['label'] = $form['#info']['filter-keys']['label'] . ' ' . $node->getTitle();
    if ($form['actions']['reset']['#access']) {
      $form['actions']['reset'] = ['#markup' => \Drupal\Core\Render\Markup::create('<div><a href="'.$form['#action'].'">Reset results list</a></div>')];
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function custom_blogs_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if ($view->id() == 'blogroll_view' && $view->current_display == 'block_2') {
    //This removes the block if the field isnt set.
    if (count($view->result) == 1 && empty($view->result[0]->_entity->get('field_blogroll')->getValue())) {
      unset($view->result[0]);
    }
  }
  if ($view->id() == 'author' && $view->current_display == 'page_1') {
    $author_display_name = '';
    if (isset($view->args[0]) && $author = user_load_by_name($view->args[0])) {
      $author_display_name = $author->get('field_user_display')->value;
      if (isset($view->args[1])) {
        $author_names = [];
        $conjunction = ' or ';
        if (strpos($view->args[1], ',') !== FALSE) {
          $author_names = explode(',', $view->args[1]);
          $conjunction = ' and ';
        }
        else if (strpos($view->args[1], '+') !== FALSE) {
          $author_names = explode('+', $view->args[1]);
        }
        else if (strpos($view->args[1], ' ') !== FALSE) {
          $author_names = explode(' ', $view->args[1]);
        }
        else {
          $author_names[] = $view->args[1];
        }
        $last = array_key_last($author_names);
        foreach ($author_names as $key => $author_name) {
          if ($author_name != $view->args[0]) {
            $join = ', ';
            if ($key == $last) {
              $join = $conjunction;
            }
            $author = user_load_by_name($author_name);
            $author_display_name .= $join . $author->get('field_user_display')->value;
          }
        }
      }
      $view->setTitle('Posts by '. $author_display_name);
    }
  }
}

/**
+ * Implements hook_views_post_render().
+ */
function custom_blogs_views_post_render(\Drupal\views\ViewExecutable $view, array &$output, \Drupal\views\Plugin\views\cache\CachePluginBase $cache) {
  if (empty(\Drupal::request()->get('keys')) && $view->id() == 'recent_posts' && $view->current_display == 'block_1') {
    //This sets the title if the search keys are empty.
    $view->setTitle('Recent Posts');
  }
}
