<?php

/**
 * @file
 * Tests the execution of hook_oembed_providers_alter().
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\oembed_providers_test\Hook\OembedProvidersHooks;

/**
 * Implements hook_oembed_providers_alter().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function oembed_providers_test_oembed_providers_alter(array &$providers) {
  \Drupal::service(OembedProvidersHooks::class)->providersAlter($providers);
}
