<?php

/**
 * @file
 * Test module for testing the paragraphs module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\paragraphs_test\Hook\ParagraphsTestHooks;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook_paragraphs_widget_actions_alter().
 */
#[LegacyHook]
function paragraphs_test_paragraphs_widget_actions_alter(&$widget_actions, &$context) {
  \Drupal::service(ParagraphsTestHooks::class)->paragraphsWidgetActionsAlter($widget_actions, $context);
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
#[LegacyHook]
function paragraphs_test_paragraph_view(array &$build, ParagraphInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  \Drupal::service(ParagraphsTestHooks::class)->paragraphView($build, $entity, $display, $view_mode);
}

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
#[LegacyHook]
function paragraphs_test_field_widget_single_element_entity_reference_paragraphs_form_alter(&$element, &$form_state, $context) {
  \Drupal::service(ParagraphsTestHooks::class)->fieldWidgetSingleElementEntityReferenceParagraphsFormAlter($element, $form_state, $context);
}
