<?php

use Drupal\views\ViewExecutable;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Markup;

function custom_configurations_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  if ($block->getBaseId() === 'views_exposed_filter_block' && $block->getDerivativeId() === 'search_blog_s_-page_2') {
    $build['#configuration']['label'] = 'Search all Blogs';
    $build['#configuration']['label_display'] = 1;
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof \Drupal\node\NodeInterface) {
      $title = $node->getTitle();
      $build['#configuration']['label'] = 'Search in ' . $title;
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function custom_configurations_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $view = $form_state->getStorage('view');
  if (($view['view']->id() == 'search_blog_s_') && ($view['view']->current_display == 'page_2')) {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof \Drupal\node\NodeInterface) {
      $nid = $node->id();
      $form['#action'] = $form['#action'] . '/' . $nid;
    }
  }
}
