<?php

/**
 * @file
 * Contains twig_vardumper.module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\twig_vardumper\Hook\TwigVardumperHooks;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function twig_vardumper_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(TwigVardumperHooks::class)->help($route_name, $route_match);
}
