<?php

/**
 * @file
 * Twig Vardumper install and update hooks.
 */

use Drupal\Component\Utility\DeprecationHelper;
use Drupal\Core\Extension\Requirement\RequirementSeverity;

/**
 * Implements hook_requirements().
 */
function twig_vardumper_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    if (!class_exists('\Symfony\Component\VarDumper\VarDumper')) {
      $requirements['vardumper_library'] = [
        'description' => t('Twig Vardumper requires the symfony/var-dumper library.'),
        'severity' => DeprecationHelper::backwardsCompatibleCall(\Drupal::VERSION, '11.2.0', fn() => RequirementSeverity::Error, fn() => REQUIREMENT_ERROR),
      ];
    }
  }

  return $requirements;
}
