<?php

/**
 * @file
 * Contains main module functions.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function link_attributes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.link_attributes':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The link attributes module provides a widget that allows users to add attributes to link fields. If you enable the Menu Link Content integration sub-module, it overtakes the core default widget for menu link content entities, allowing you to set attributes on menu links.') . '</p>';
      return $output;
  }
}
