<?php
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_openid_connect_pre_authorize().
 */
function custom_openid_openid_connect_pre_authorize($account, array $context) {
  $uname = NULL;
  if (isset($context['userinfo']['preferred_username']) || isset($context['userinfo']['email'])) {
    $uname = $context['userinfo']['preferred_username'];
    if (empty($uname)) {
      $uname = explode('@', $context['userinfo']['email']);
      if ($uname[1] == 'umich.edu') {
        $uname = $uname[0];
      }
      else {
        $uname = $context['userinfo']['email'];
      }
    }
// UNCOMMENT 3 LINES BELOW and replace YOUR_USERNAME_HERE and USER_YOU_WANT_TO_BE_HERE with appropriate values
//    if (in_array($uname,['YOUR_USERNAME_HERE']) && strpos($_SERVER['HTTP_USER_AGENT'], 'Chrome')) {
//      return user_load_by_name('USER_YOU_WANT_TO_BE_HERE');
//    }
// IF YOU WANT TO ACT AS A NEW USER, go to hook_openid_connect_userinfo_alter below and add
// if ($uname == 'YOUR_USERNAME_HERE') { $uname = 'USER_YOU_WANT_TO_BE_HERE'; }
// above
// $userinfo['name'] = $uname;
  }
  if ((is_bool($account) || !$account) && $uname) {
    $account = user_load_by_name($uname);
  }
  // Allow access only for current users
  if (($account && !$account->isBlocked() && $account->hasRole('authenticated'))
    && $context['plugin_id'] == 'generic'
  ) {
    return $account;
  }
  // Deny all other users.
//  return FALSE;
}

/**
 * Implements hook_openid_connect_userinfo_alter().
 */
function custom_openid_openid_connect_userinfo_alter(array &$userinfo, array $context) {
  // Add some custom information.
  if ($context['plugin_id'] == 'generic') {
    $uname = explode('@', $userinfo['email']);
    if ($uname[1] == 'umich.edu') {
      $uname = $uname[0];
    }
    else {
      $uname = $userinfo['email'];
    }
    $userinfo['name'] = $uname;
  }
}
