<?php

/**
 * @file
 * Main module file for the Paragraphs Library module.
 */

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Database\Query\SelectInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\paragraphs_library\Hook\ParagraphsLibraryHooks;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\paragraphs\ParagraphInterface;
use Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget;
use Drupal\views\ViewExecutable;
use Drupal\paragraphs_library\Entity\LibraryItem;
use Drupal\Core\Field\WidgetBase;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\paragraphs\ParagraphsTypeInterface;

/**
 * Implements hook_modules_installed().
 */
#[LegacyHook]
function paragraphs_library_modules_installed($modules) {
  \Drupal::service(ParagraphsLibraryHooks::class)->modulesInstalled($modules);
}

/**
 * Implements hook_paragraphs_widget_actions_alter().
 */
#[LegacyHook]
function paragraphs_library_paragraphs_widget_actions_alter(&$widget_actions, &$context) {
  \Drupal::service(ParagraphsLibraryHooks::class)->paragraphsWidgetActionsAlter($widget_actions, $context);
}

/**
 * Make library item submit callback.
 *
 * @param array $form
 *   The element form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 */
function paragraphs_library_make_library_item_submit(array $form, FormStateInterface $form_state) {
  $submit = ParagraphsWidget::getSubmitElementInfo($form, $form_state, ParagraphsWidget::ACTION_POSITION_ACTIONS);

  // Replacing element in the array.
  $library_item = LibraryItem::createFromParagraph($submit['widget_state']['paragraphs'][$submit['delta']]['entity']);
  $library_item->save();

  // Replace this paragraph with a library reference one.
  $paragraph_item = [
    'entity' => Paragraph::create([
      'type' => 'from_library',
      'field_reusable_paragraph' => $library_item,
    ]),
    'display' => $submit['widget_state']['paragraphs'][$submit['delta']]['display'],
    'mode' => 'edit',
  ];

  $submit['widget_state']['paragraphs'][$submit['delta']] = $paragraph_item;
  WidgetBase::setWidgetState($submit['parents'], $submit['field_name'], $form_state, $submit['widget_state']);
  $form_state->setRebuild();
}

/**
 * Implements hook_preprocess_HOOK().
 */
#[LegacyHook]
function paragraphs_library_preprocess_paragraph(&$variables) {
  \Drupal::service(ParagraphsLibraryHooks::class)->preprocessParagraph($variables);
}

/**
 * Implements hook_views_pre_render().
 */
#[LegacyHook]
function paragraphs_library_views_pre_render(ViewExecutable $view) {
  \Drupal::service(ParagraphsLibraryHooks::class)->viewsPreRender($view);
}

/**
 * Counts the usage across all entities.
 *
 * @param array $usage_data
 *   Array of usage data returned from Entity Usage service.
 *
 * @return int
 *   Returns the count of entity usage across all entities.
 *
 * @see \Drupal\entity_usage\EntityUsageInterface::listSources()
 */
function _paragraphs_library_count_usage(array $usage_data) {
  $count = 0;
  foreach ($usage_data as $entities) {
    // We only want to register usages by different entities, ignoring usages
    // accross revisions / translations / fields of the same entity.
    $count += count($entities);
  }

  return $count;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
#[LegacyHook]
function paragraphs_library_form_paragraphs_type_form_alter(&$form, FormStateInterface $form_state) {
  \Drupal::service(ParagraphsLibraryHooks::class)->formParagraphsTypeFormAlter($form, $form_state);
}

/**
 * Entity builder for the paragraphs type form with group property.
 *
 * @see paragraphs_library_form_paragraphs_type_form_alter()
 */
function paragraphs_library_form_paragraphs_type_form_builder($entity_type, ParagraphsTypeInterface $type, &$form, FormStateInterface $form_state) {
  if ($form_state->getValue('allow_library_conversion')) {
    $type->setThirdPartySetting('paragraphs_library', 'allow_library_conversion', $form_state->getValue('allow_library_conversion'));
  }
  else {
    $type->unsetThirdPartySetting('paragraphs_library', 'allow_library_conversion');
  }
}

/**
 * Convert library item submit callback.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 */
function paragraphs_library_library_item_unlink_submit(array $form, FormStateInterface $form_state) {
  $submit = ParagraphsWidget::getSubmitElementInfo($form, $form_state, ParagraphsWidget::ACTION_POSITION_ACTIONS);

  $submit['widget_state']['original_deltas'] = array_merge($submit['widget_state']['original_deltas'], ['1' => 1]);
  /** @var \Drupal\Paragraphs\ParagraphInterface $paragraph */
  $paragraph = $submit['widget_state']['paragraphs'][$submit['delta']]['entity'];

  $original_paragraph = NULL;
  if ($paragraph->hasField('field_reusable_paragraph')) {
    /** @var \Drupal\paragraphs_library\Entity\LibraryItem $library_item */
    $library_item = $paragraph->get('field_reusable_paragraph')->entity;
    if ($library_item) {
      $original_paragraph = $library_item->get('paragraphs')->entity;
    }
  }

  // Do nothing in case we fail to get the original paragraph.
  if (!$original_paragraph instanceof ParagraphInterface) {
    return;
  }

  // Make a copy of the paragraph. Use the Replicate module, if it is enabled.
  if (\Drupal::hasService('replicate.replicator')) {
    $duplicate_paragraph = \Drupal::getContainer()->get('replicate.replicator')->cloneEntity($original_paragraph);
  }
  else {
    $duplicate_paragraph = $original_paragraph->createDuplicate();
  }

  // Ensure correct parent information before the unlinked paragraph is saved.
  if ($paragraph->getParentEntity()) {
    $duplicate_paragraph->setParentEntity($paragraph->getParentEntity(), $paragraph->get('parent_field_name')->value);
  }

  $paragraph_item = [
    'entity' => $duplicate_paragraph,
    'display' => $submit['widget_state']['paragraphs'][$submit['delta']]['display'],
    'mode' => 'edit',
  ];

  $submit['widget_state']['paragraphs'][$submit['delta']] = $paragraph_item;
  WidgetBase::setWidgetState($submit['parents'], $submit['field_name'], $form_state, $submit['widget_state']);
  $form_state->setRebuild();
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
#[LegacyHook]
function paragraphs_library_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  \Drupal::service(ParagraphsLibraryHooks::class)->entityBundleFieldInfoAlter($fields, $entity_type, $bundle);
}

/**
 * Implements hook_help().
 */
#[LegacyHook]
function paragraphs_library_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(ParagraphsLibraryHooks::class)->help($route_name, $route_match);
}

/**
 * Implements hook_query_TAG_alter().
 */
function paragraphs_library_query_paragraphs_library_item_access_alter(AlterableInterface $query): void {
  if ($query instanceof SelectInterface && (!\Drupal::currentUser()->hasPermission('administer paragraphs library') && !\Drupal::currentUser()->hasPermission('view any unpublished content'))) {
    $tables = $query->getTables();

    $base_alias = NULL;
    $data_alias = $query->getMetaData('access_alias');

    // If the table to filter on is not explicitly provided, try to find it
    // prefer non-revision_tables.
    if (!$data_alias) {
      foreach ($tables as $table) {
        if ($table['table'] === 'paragraphs_library_item') {
          $base_alias = $table['alias'];
        }
        elseif (!$base_alias && $table['table'] === 'paragraphs_library_item_revision') {
          $base_alias = $table['alias'];
        }
        elseif ($table['table'] === 'paragraphs_library_item_field_data') {
          $data_alias = $table['alias'];
        }
        elseif (!$data_alias && $table['table'] === 'paragraphs_library_item_field_revision') {
          $data_alias = $table['alias'];
        }
      }
    }

    if ($base_alias && !$data_alias) {
      $data_alias = $query->innerJoin('paragraphs_library_item_field_data', 'data_table', $base_alias . '.id = %alias.id AND %alias.default_langcode = 1');
    }

    if ($data_alias) {
      $query->condition($data_alias . '.status', 1);
    }

  }
}
