<?php

/**
 * @file
 * Implements the link_attributes_menu_link_content functionality.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function link_attributes_menu_link_content_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'menu_link_content') {
    $fields['link']->setDisplayOptions('form', [
      'type' => 'link_attributes',
      'weight' => -2,
    ]);
  }
}

/**
 * Implements hook_help().
 */
function link_attributes_menu_link_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.link_attributes_menu_link_content':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The "link_attributes_menu_link_content" sub-module provides a widget that allows users to add attributes to menu links. It overtakes the core default widget for menu link content entities, allowing you to set attributes on menu links.') . '</p>';
      return $output;
  }
}
