mimemail.settings:
  type: config_object
  mapping:
    name:
      type: string
      label: 'Sender name'
    mail:
      type: email
      label: 'Sender email address'
    simple_address:
      type: boolean
      label: 'Use simple format for all recipient email addresses'
    sitestyle:
      type: boolean
      label: 'Gather all style sheets when no mail.css is found in the default theme directory'
    textonly:
      type: boolean
      label: 'Disables the use of email messages with graphics and styles, all messages will be converted to plain text'
    linkonly:
      type: boolean
      label: 'Disables the embedding of images, all images will be links to external content'
    user_plaintext_field:
      type: string
      label: 'Machine name of a Boolean field on the User entity used to indicate the user only wants plain text email'
    format:
      type: string
      label: 'Email format'
    preserve_class:
      type: boolean
      label: 'Whether to preserve CSS class attributes when inlining CSS using mimemail_compress'
    advanced:
      type: mapping
      label: 'Advanced features - do not enable unless you know what you are doing'
      mapping:
        incoming:
          type: boolean
          label: 'Process incoming messages posted to this site'
        key:
          type: string
          label: 'Message validation string'
