<?php

/**
 * @file
 * Module file for the view_block_filter_view module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_help().
 */
function views_block_filter_block_help($path, $arg) {
  switch ($path) {
    case 'help.page.views_block_filter_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a utility Drupal extension that allows you to configure exposed filters on block display views to be displayed
and placed as standard blocks. Although this is possible by default for page display views, this functionality is not
possible for block display views without this module.</br></br>
This extension requires no configuration. Just install it and it works; you should see an "exposed filter in block"
option under the "advanced" pane of the Views UI for all block display views.') . '</p>';
      $output .= '<p>' . t('For more information, see the <a href="https://www.drupal.org/project/views_block_filter_block">Views Block Exposed Filter Blocks module</a>.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_views_plugins_display_alter().
 */
function views_block_filter_block_views_plugins_display_alter(array &$plugins) {
  // Force the block display plugin to use our block display plugin.
  $plugins['block']['class'] = 'Drupal\views_block_filter_block\Plugin\views\display\ViewsBlockFilterBlockPluginDisplayBlock';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function views_block_filter_block_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Never enable a reset button that has already been disabled.
  if (!isset($form['actions']['reset']['#access']) || $form['actions']['reset']['#access'] === TRUE) {
    $form['actions']['reset']['#access'] = !empty(Element::getVisibleChildren($form));
  }
}
