<?php

/**
 * @file
 * Install file for the view_block_filter_view module.
 */

use Drupal\Core\Extension\ModuleInstallerInterface;

/**
 * Installs new ctools_views dependency.
 */
function views_block_filter_block_update_8001(&$sandbox): void {
  $moduleInstaller = \Drupal::service('module_installer');
  assert($moduleInstaller instanceof ModuleInstallerInterface);
  $moduleInstaller->install(['ctools_views']);
}
