# Schema for the configuration files of the Passwordless module.

passwordless.settings:
  type: mapping
  label: 'Passwordless settings'
  mapping:
    passwordless_add_css:
      type: boolean
      label: 'Include stylesheet on login page'
    passwordless_show_help:
      type: boolean
      label: 'Show Passwordless help'
    passwordless_help_link_text:
      type: label
      label: 'Passwordless help-link text'
    passwordless_help_text:
      type: mapping
      label: 'Passwordless help-page text'
      mapping:
        value:
          type: text
    passwordless_toggle_sent_page:
      type: boolean
      label: 'Enable confirmation page'
    passwordless_sent_title_text:
      type: label
      label: 'Confirmation-page title'
    passwordless_sent_page_text:
      type: mapping
      label: 'Confirmation-page text'
      mapping:
        value:
          type: text
    langcode:
      type: string
      label: 'Default language'