name: Configuration development
type: module
description: 'Helps developers work with configuration.'
package: Configuration
# version: VERSION
core_version_requirement: ^9.3 || ^10 || ^11
configure: config_devel.settings
dependencies:
  - drupal:config

# Information added by Drupal.org packaging script on 2024-09-24
version: '8.x-1.10'
project: 'config_devel'
datestamp: 1727184346
