name: Configuration development
type: module
description: 'Helps developers work with configuration.'
package: Configuration
# version: VERSION
core_version_requirement: ^10 || ^11
configure: config_devel.settings
dependencies:
  - drupal:config

# Information added by Drupal.org packaging script on 2026-07-29
version: '8.x-1.12'
project: 'config_devel'
datestamp: 1785339744
